### ISSUE TITLE
Update model to be compatible with newer io.kubernetes client-java

### ISSUE THREAD

**Issue by dzhi-lyft** [openkruise/client-java#2]
The models included, like KruiseAppsV1alpha1CloneSet, are compatible with io.kubernetes client-java 5.0.0. It will lead to error like java.lang.ClassNotFoundException: io.kubernetes.client.models.V1ObjectMeta if later version of io.kubernetes client-java is used.

Comments in the model code suggest they were generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen. However I don't see clear instructions on how to re-generate the models based on newer version of io.kubernetes client-java, like 11.0.0.

How to generate new models that are compatible with more recent io.kubernetes client-java?

**Comment by dzhi-lyft** [comment]
Actually the only changes needed are replacing 
"io.kubernetes.client.models" with "io.kubernetes.client.**openapi**.models" in total 29 files.

**Comment by qiankunli** [comment]
> Actually the only changes needed are replacing
> "io.kubernetes.client.models" with "io.kubernetes.client.**openapi**.models" in total 29 files.
@dzhi-lyft 哥们你这个问题解决了嘛，我们最近也有使用java 来发布openkruise 的需求

**Comment by dzhi-lyft** [comment]
@qiankunli I built and use a private version with above changes. Following is the patch file in case it helps.

[0001-Update-model-to-be-compatible-with-io.kubernetes-cli.patch.txt](https://github.com/openkruise/client-java/files/5888912/0001-Update-model-to-be-compatible-with-io.kubernetes-cli.patch.txt)

**Comment by FillZpp** [comment]
@qiankunli @dzhi-lyft I have generate client-java with the latest apis and fix this compatible issue. Thanks for reporting.
