### ISSUE TITLE
Can i get an example code snippet of "watch" on listNamespacedCustomObject

### ISSUE THREAD

**Issue by rajkagrawal** [openkruise/client-java#7]
@FillZpp i want to watch on delete event of cloneset. Can you help me with some code snippet around watch.

**Comment by FillZpp** [comment]
@rajaanova `openkruise/client-java` only provides the API definition of Kruise CRDs, you should use [kubernetes-client/java](https://github.com/kubernetes-client/java) as client to read/write/watch the CR objects.

So you may look at the [watch example](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/WatchExample.java) or [informer example](https://github.com/kubernetes-client/java/blob/master/examples/examples-release-13/src/main/java/io/kubernetes/client/examples/InformerExample.java),
and chagne `CoreV1Api .listNamespaceCall` to `CustomObjectsApi. listNamespacedCustomObject`.
