### ISSUE TITLE
What's the replacement object for the deleted io/openkruise/client/JSON.java?

### ISSUE THREAD

**Issue by dzhi-lyft** [openkruise/client-java#9]
It appears that files like src/main/java/io/openkruise/client/JSON.java was deleted on 2021-12-07. Usage of such file is to parse the customized JSON object like cloneset. Wonder what's the replacement object to use for such purpose? @FillZpp

**Comment by FillZpp** [comment]
@dzhi-lyft Yep, it has been removed.

Actually, the only thing you should import from `io.openkruise:client-java` is the CRD models in `io.openkruise.client.models.*`. Other things such as `ApiClient`, `CustomObjectsApi`  or `JSON`, you have to import them from the standard `io.kubernetes:client-java`, e.g. `io.kubernetes.client.openapi.JSON`.

**Comment by dzhi-lyft** [comment]
Thanks and it makes sense. I was checking a wrong repository yesterday and didn't see kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java.
